// Command thirdpartynotices writes THIRD_PARTY_NOTICES.md: the licence and
// NOTICE text of every Go module compiled into a binary.
//
// MockAgents ships statically linked binaries and a container image. MIT, BSD
// and ISC require their copyright notice to travel with binary copies, and
// Apache-2.0 §4(d) requires a dependency's NOTICE text to be passed on, so the
// release archives and the image carry this file (2026-10-06 review O-02). It
// is generated at build time from the module cache rather than committed, so
// it cannot drift from go.mod.
//
// Usage:
//
//	go run ./tools/thirdpartynotices [-pkg ./cmd/mockagents] [-o THIRD_PARTY_NOTICES.md]
//
// It fails when a dependency has no recognisable licence file, so a new
// dependency cannot ship without one being found.
package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	pkg := flag.String("pkg", "./cmd/mockagents", "package whose dependencies are listed")
	out := flag.String("o", "THIRD_PARTY_NOTICES.md", "output file ('-' for stdout)")
	flag.Parse()

	mods, err := listModules(*pkg)
	if err != nil {
		fmt.Fprintln(os.Stderr, "thirdpartynotices:", err)
		os.Exit(1)
	}
	var buf bytes.Buffer
	if err := render(&buf, mods); err != nil {
		fmt.Fprintln(os.Stderr, "thirdpartynotices:", err)
		os.Exit(1)
	}
	if *out == "-" {
		_, _ = os.Stdout.Write(buf.Bytes())
		return
	}
	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "thirdpartynotices:", err)
		os.Exit(1)
	}
	fmt.Printf("thirdpartynotices: wrote %d modules to %s\n", len(mods), *out)
}

// module is one third-party module linked into the binary.
type module struct {
	Path, Version, Dir string
}

// listModules returns the non-main modules that provide packages to pkg,
// sorted by path. Only modules that are actually compiled in are listed,
// unlike `go list -m all`, which includes test-only and unused requirements.
func listModules(pkg string) ([]module, error) {
	cmd := exec.Command("go", "list", "-deps",
		"-f", `{{with .Module}}{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{end}}{{end}}`, pkg)
	cmd.Stderr = os.Stderr
	outBytes, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list: %w", err)
	}
	return parseModules(outBytes), nil
}

// parseModules de-duplicates `go list -deps` lines of "path version dir".
func parseModules(out []byte) []module {
	seen := map[string]module{}
	sc := bufio.NewScanner(bytes.NewReader(out))
	for sc.Scan() {
		fields := strings.SplitN(strings.TrimSpace(sc.Text()), " ", 3)
		if len(fields) < 2 {
			continue
		}
		m := module{Path: fields[0], Version: fields[1]}
		if len(fields) == 3 {
			m.Dir = fields[2]
		}
		seen[m.Path] = m
	}
	mods := make([]module, 0, len(seen))
	for _, m := range seen {
		mods = append(mods, m)
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].Path < mods[j].Path })
	return mods
}

// noticeFiles returns the licence and NOTICE files at the top of a module
// directory, licence files first.
func noticeFiles(dir string) (licences, notices []string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		switch kind := classify(e.Name()); kind {
		case "licence":
			licences = append(licences, filepath.Join(dir, e.Name()))
		case "notice":
			notices = append(notices, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(licences)
	sort.Strings(notices)
	return licences, notices
}

// classify recognises a licence or NOTICE file by name.
func classify(name string) string {
	upper := strings.ToUpper(name)
	base := strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(upper, ".MD"), ".TXT"), ".RST")
	switch {
	case base == "NOTICE":
		return "notice"
	case base == "LICENSE", base == "LICENCE", base == "COPYING", base == "UNLICENSE",
		strings.HasPrefix(base, "LICENSE-"), strings.HasPrefix(base, "LICENSE."),
		strings.HasPrefix(base, "COPYING."):
		return "licence"
	}
	return ""
}

var errNoLicence = errors.New("no licence file found")

func render(w io.Writer, mods []module) error {
	fmt.Fprintln(w, "# Third-party notices")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "MockAgents is licensed under the Apache License 2.0 (see LICENSE and NOTICE).")
	fmt.Fprintln(w, "The binary statically links the Go modules below; each one's licence and")
	fmt.Fprintln(w, "NOTICE text follows. Generated by tools/thirdpartynotices — do not edit.")
	fmt.Fprintln(w)
	var missing []string
	for _, m := range mods {
		licences, notices := noticeFiles(m.Dir)
		if len(licences) == 0 {
			missing = append(missing, m.Path+"@"+m.Version)
			continue
		}
		fmt.Fprintf(w, "## %s %s\n\n", m.Path, m.Version)
		for _, f := range append(licences, notices...) {
			data, err := os.ReadFile(f)
			if err != nil {
				return err
			}
			fmt.Fprintf(w, "### %s\n\n```text\n%s\n```\n\n", filepath.Base(f), strings.TrimRight(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n"))
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("%w for: %s", errNoLicence, strings.Join(missing, ", "))
	}
	return nil
}
