// Command handoffcatalog refreshes the source inventories used by the handoff
// documentation. Run from the repository root. It never changes runtime code.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

const outDir = "docs/handoff/reference"

type route struct{ pattern, handler, file, surface string }

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	filesRaw, err := exec.Command("git", "ls-files", "-z").Output()
	if err != nil {
		return err
	}
	files := strings.Split(strings.TrimSuffix(string(filesRaw), "\x00"), "\x00")
	sort.Strings(files)
	var inventory, models, deps strings.Builder
	inventory.WriteString("# Tracked source inventory\n\nGenerated by `go run ./tools/handoffcatalog` from tracked files; this is an inventory, not a claim of line-by-line review. Newly added, untracked files appear after they are tracked and the catalog is regenerated. See [review scope](../../reviews/2026-09-18-review-summary.md).\n\n| File | Category |\n| --- | --- |\n")
	models.WriteString("# Go model field dictionary\n\nGenerated from named Go structs with JSON or YAML tags in production source (including SDK Go types). Tables preserve exact tags and Go field types. `omitempty` describes serialization, **not** validation or requiredness. Pointer fields distinguish omission from explicit zero. `-` excludes a field. Untagged embedded fields are shown where present. Inline anonymous request structs and dynamic maps remain defined in the linked handler source; consult the [API guide](../api.md) for wire behavior and [data models](../data-models.md) for validation, relationships, and custom serializers. Source comments below are discovery aids and may describe historical intent; the behavioral guides take precedence over stale comments.\n\n")
	deps.WriteString("# Internal dependency map\n\nGenerated from non-test Go imports. These are direct package dependencies, not runtime network calls. Third-party versions remain in [go.mod](../../../go.mod); SDK and GUI dependencies remain in their package manifests.\n\n| Package | Direct internal / SDK Go imports |\n| --- | --- |\n")
	fset := token.NewFileSet()
	var routes []route
	var unresolvedRoutes []string
	floors := map[string]string{}
	imports := map[string]map[string]bool{}
	modelCount := 0
	for _, file := range files {
		category := "source/configuration"
		if strings.Contains(file, "test") || strings.Contains(file, "spec.") {
			category = "test/fixture"
		}
		if strings.HasSuffix(file, ".md") {
			category = "documentation"
		}
		if strings.Contains(file, "lock") {
			category = "dependency lock"
		}
		fmt.Fprintf(&inventory, "| [%s](../../../%s) | %s |\n", file, file, category)
		if !strings.HasSuffix(file, ".go") || strings.HasSuffix(file, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
		if err != nil {
			return err
		}
		pkg := filepath.ToSlash(filepath.Dir(file))
		if imports[pkg] == nil {
			imports[pkg] = map[string]bool{}
		}
		for _, im := range f.Imports {
			s, _ := strconv.Unquote(im.Path.Value)
			if strings.HasPrefix(s, "github.com/mockagents/mockagents/") {
				imports[pkg][strings.TrimPrefix(s, "github.com/mockagents/mockagents/")] = true
			}
		}
		constants := map[string]string{}
		ast.Inspect(f, func(n ast.Node) bool {
			if vs, ok := n.(*ast.ValueSpec); ok {
				for i, name := range vs.Names {
					if i < len(vs.Values) {
						if s, ok := eval(vs.Values[i], constants); ok {
							constants[name.Name] = s
						}
					}
				}
			}
			return true
		})
		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, sp := range gen.Specs {
				ts, ok := sp.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				tagged := false
				for _, field := range st.Fields.List {
					if field.Tag != nil {
						tag, _ := strconv.Unquote(field.Tag.Value)
						if strings.Contains(tag, "json:") || strings.Contains(tag, "yaml:") {
							tagged = true
						}
					}
				}
				if !tagged {
					continue
				}
				modelCount++
				fmt.Fprintf(&models, "## %s.%s\n\nSource: [%s](../../../%s#L%d).\n\n", pkg, ts.Name.Name, file, file, fset.Position(ts.Pos()).Line)
				models.WriteString("| Go field | Go type | JSON tag | YAML tag | Source field note |\n| --- | --- | --- | --- | --- |\n")
				for _, field := range st.Fields.List {
					tag := ""
					if field.Tag != nil {
						tag, _ = strconv.Unquote(field.Tag.Value)
					}
					jt, yt := reflect.StructTag(tag).Get("json"), reflect.StructTag(tag).Get("yaml")
					if jt == "" && yt == "" && len(field.Names) > 0 {
						continue
					}
					names := []string{}
					for _, n := range field.Names {
						names = append(names, n.Name)
					}
					if len(names) == 0 {
						names = append(names, "(embedded)")
					}
					note := strings.TrimSpace(field.Doc.Text() + " " + field.Comment.Text())
					fmt.Fprintf(&models, "| `%s` | `%s` | `%s` | `%s` | %s |\n", strings.Join(names, ", "), clean(expr(fset, field.Type)), clean(jt), clean(yt), clean(note))
				}
				models.WriteString("\n")
			}
		}
		ast.Inspect(f, func(n ast.Node) bool {
			if kv, ok := n.(*ast.KeyValueExpr); ok && file == "internal/server/route_authz.go" {
				if key, ok := eval(kv.Key, constants); ok {
					floors[key] = expr(fset, kv.Value)
				}
			}
			if cl, ok := n.(*ast.CompositeLit); ok && strings.HasPrefix(file, "internal/adapter/") {
				pattern, handler := "", ""
				for _, el := range cl.Elts {
					kv, ok := el.(*ast.KeyValueExpr)
					if !ok {
						continue
					}
					id, ok := kv.Key.(*ast.Ident)
					if !ok {
						continue
					}
					if id.Name == "Pattern" {
						var resolved bool
						pattern, resolved = eval(kv.Value, constants)
						if !resolved {
							unresolvedRoutes = append(unresolvedRoutes, fmt.Sprintf("%s:%d", file, fset.Position(kv.Pos()).Line))
						}
					}
					if id.Name == "Handler" {
						handler = expr(fset, kv.Value)
					}
				}
				if pattern != "" {
					routes = append(routes, route{pattern, handler, file, "provider"})
				}
			}
			if call, ok := n.(*ast.CallExpr); ok {
				sel, ok := call.Fun.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				idx := -1
				surface := "management"
				switch sel.Sel.Name {
				case "mountManaged":
					idx = 1
				case "Handle", "HandleFunc":
					idx = 0
					surface = "auxiliary"
				}
				if idx >= 0 && idx+1 < len(call.Args) {
					if pattern, ok := eval(call.Args[idx], constants); ok && strings.Contains(pattern, "/") {
						if file == "internal/server/server.go" || file == "cmd/mockagents/mcp.go" || file == "cmd/mockagents/a2a.go" {
							routes = append(routes, route{pattern, expr(fset, call.Args[idx+1]), file, surface})
						}
					}
				}
			}
			return true
		})
	}
	if len(unresolvedRoutes) > 0 {
		return fmt.Errorf("unresolved adapter route expressions: %s", strings.Join(unresolvedRoutes, ", "))
	}
	pkgs := []string{}
	for pkg := range imports {
		pkgs = append(pkgs, pkg)
	}
	sort.Strings(pkgs)
	for _, pkg := range pkgs {
		names := []string{}
		for n := range imports[pkg] {
			names = append(names, "`"+n+"`")
		}
		sort.Strings(names)
		fmt.Fprintf(&deps, "| `%s` | %s |\n", pkg, strings.Join(names, ", "))
	}
	sort.Slice(routes, func(i, j int) bool {
		if routes[i].surface != routes[j].surface {
			return routes[i].surface < routes[j].surface
		}
		return routes[i].pattern < routes[j].pattern
	})
	var api strings.Builder
	api.WriteString("# Mounted HTTP route catalog\n\nGenerated from adapter route literals and main/MCP/A2A mounting calls, including Chroma's composed path. This is the built-in route superset; [API documentation](../api.md) explains conditional mounts, bodies, errors, auth, and RPC methods. Management floors apply only in multi-tenant mode; `roleOpen` means any authenticated role except explicitly public probes. Provider routes allow anonymous access and optionally resolve valid MockAgents credentials. Standalone MCP/A2A listeners do not inherit the main server's middleware. `GET` ServeMux patterns also accept `HEAD`.\n\n| Pattern | Surface / role floor | Handler | Source |\n| --- | --- | --- | --- |\n")
	seen := map[string]bool{}
	for _, r := range routes {
		key := r.file + " " + r.pattern
		if seen[key] {
			continue
		}
		seen[key] = true
		floor := r.surface
		if f := floors[r.pattern]; f != "" {
			floor = f
		}
		handler := r.handler
		if strings.Contains(handler, "func(") {
			handler = "inline handler"
		}
		fmt.Fprintf(&api, "| `%s` | `%s` | `%s` | [%s](../../../%s) |\n", clean(r.pattern), floor, clean(handler), r.file, r.file)
	}
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}
	outputs := map[string]string{"source-inventory.md": inventory.String(), "model-fields.md": models.String(), "dependencies.md": deps.String(), "routes.md": api.String()}
	for name, body := range outputs {
		if err := os.WriteFile(filepath.Join(outDir, name), []byte(strings.TrimRight(body, "\n")+"\n"), 0644); err != nil {
			return err
		}
	}
	fmt.Printf("handoffcatalog: %d tagged models, %d route mounts, %d Go packages; four catalogs refreshed\n", modelCount, len(seen), len(pkgs))
	return nil
}

func expr(fset *token.FileSet, n ast.Node) string {
	var b bytes.Buffer
	_ = printer.Fprint(&b, fset, n)
	return b.String()
}
func clean(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	s = strings.ReplaceAll(s, "|", "&#124;")
	s = strings.ReplaceAll(s, "{{", "&#123;&#123;")
	s = strings.ReplaceAll(s, "{%", "&#123;%")
	return s
}
func eval(e ast.Expr, vars map[string]string) (string, bool) {
	switch v := e.(type) {
	case *ast.BasicLit:
		if v.Kind == token.STRING {
			s, err := strconv.Unquote(v.Value)
			return s, err == nil
		}
	case *ast.Ident:
		s, ok := vars[v.Name]
		return s, ok
	case *ast.BinaryExpr:
		if v.Op == token.ADD {
			a, ok := eval(v.X, vars)
			b, ok2 := eval(v.Y, vars)
			return a + b, ok && ok2
		}
	}
	return "", false
}
